### ISSUE TITLE
AWS CodeBuild OS update

### ISSUE THREAD

**Issue by baptiste-lunii** [ohoareau/cd-gatsby#1]
The future OS update required to add `VOLUME /var/lib/docker` in DockerImage

> We are reaching out to you because you ran a CodeBuild build using a custom Docker image in the last 4 weeks. AWS CodeBuild is updating the operating system used for the CodeBuild's build fleet from Amazon Linux 1 to Amazon Linux 2, starting September 27, 2021. This update will also result in the default Docker storage driver to be updated, which may impact your custom Docker image’s ability to run in CodeBuild. Specifically, if your custom Docker image does not include the VOLUME parameter, your build will fail after we upgrade the default Docker storage driver. To ensure your custom Docker images can continue to run after the storage driver upgrade, please validate that your Dockerfile includes the following parameter: VOLUME /var/lib/docker. Please make this change to ensure your builds are unaffected during this update process. For an example, see https://github.com/jpetazzo/dind/blob/master/Dockerfile

```DockerFile
...
VOLUME /var/lib/docker

WORKDIR /code
...
```

**Comment by ohoareau** [comment]
It seems that is required yes, I'll update it soon.
